Project-3/Models/TicketNotification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project_3.Models
{
    public class TicketNotification
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string ReceipentId { get; set; }
        public string SenderId { get; set; }
        public string NotificationBody { get; set; }
        public bool IsRead { get; set; }
        public DateTime Created { get; set; }

        public virtual Ticket Ticket { get; set; }
        public virtual ApplicationUser Receipent { get; set; }
        public virtual ApplicationUser Sender { get; set; }
    }
}

Project-3/Controllers/TicketNotificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_3.Helpers;
using Project_3.Models;

namespace Project_3.Controllers
{
    public class TicketNotificationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
     

        // GET: TicketNotifications
        public ActionResult Dismiss(int id)
        {
            var notification = db.TicketNotifications.Find(id);
            notification.IsRead = true;
            db.SaveChanges();
            return RedirectToAction("Dashboard", "Home");


        }
        public ActionResult Index()
        {
           
            return View(NotificationHelper.UsersAllNotification());
        }

        // GET: TicketNotifications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketNotification ticketNotification = db.TicketNotifications.Find(id);
            if (ticketNotification == null)
            {
                return HttpNotFound();
            }
            return View(ticketNotification);
        }

        // GET: TicketNotifications/Create
        public ActionResult Create()
        {
            ViewBag.ReceipentId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "OwnerUserId");
            return View();
        }

        // POST: TicketNotifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,ReceipentId,NotificationBody,IsRead")] TicketNotification ticketNotification)
        {
            if (ModelState.IsValid)
            {
                ticketNotification.Created = DateTime.Now;
                db.TicketNotifications.Add(ticketNotification);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ReceipentId = new SelectList(db.Users, "Id", "FirstName", ticketNotification.ReceipentId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "OwnerUserId", ticketNotification.TicketId);
            return View(ticketNotification);
        }

        // GET: TicketNotifications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketNotification ticketNotification = db.TicketNotifications.Find(id);
            if (ticketNotification == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReceipentId = new SelectList(db.Users, "Id", "FirstName", ticketNotification.ReceipentId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "OwnerUserId", ticketNotification.TicketId);
            return View(ticketNotification);
        }

        // POST: TicketNotifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,ReceipentId,NotificationBody,IsRead")] TicketNotification ticketNotification)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticketNotification).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ReceipentId = new SelectList(db.Users, "Id", "FirstName", ticketNotification.ReceipentId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "OwnerUserId", ticketNotification.TicketId);
            return View(ticketNotification);
        }

        // GET: TicketNotifications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TicketNotification ticketNotification = db.TicketNotifications.Find(id);
            if (ticketNotification == null)
            {
                return HttpNotFound();
            }
            return View(ticketNotification);
        }

        // POST: TicketNotifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? notifyId)
        {
            TicketNotification ticketNotification = db.TicketNotifications.Find(notifyId);
            db.TicketNotifications.Remove(ticketNotification);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project-3/Views/TicketNotifications/Delete.cshtml
@model Project_3.Models.TicketNotification

@{
    ViewBag.Title = "Delete";
}


        @using (Html.BeginForm("Delete", "TicketNotifications", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
           @Html.Hidden("deleteId", Model.Id)
    <div class="form-group" style="padding-top:20px">
        
        <div class="col-md-offset-2 col-md-10">
            <h5>Are you sure you want to delete this?</h5>
            <button type="submit" class="btn btn-danger">DELETE</button>
        </div>
    </div>
        }
   

Project-3/Views/TicketNotifications/Index.cshtml
@model IEnumerable<Project_3.Models.TicketNotification>

@{
    ViewBag.Title = "Index";
}

<section role="main" class="content-body dash">
    <header class="page-header">
        <h2>@ViewBag.Title</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="@Url.Action("Dashboard","Home")">
                        <i class="fa fa-home"></i>   <span> Go to DashBoard</span>
                    </a>
                </li>

                <li style="padding-right:10px"><span>@ViewBag.Title</span></li>
            </ol>

        </div>
    </header>
    <div class="row">
        <h2 class="htwo"></h2>
    </div>

    <div class="panel-body">
        <section class="panel panel-group">

            <div id="accordion">
                <div class="panel panel-accordion panel-accordion-first">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">
                                <i class="fa fa-check htwo"></i> All NOTIFICATIONS
                            </a>
                        </h4>
                    </div>
               
                        <div id="collapse1One" class="accordion-body collapse in">
                            <div class="panel-body">

                                @foreach (var item in Model)
                                {
                                    <ul class="widget-todo-list">

                                        <li class="text-dark">


                                            <div>
                                                <p class="m-none mail-date text-bold">@item.Sender.FullName</p>


                                                <label class="todo-label"><span>@item.NotificationBody</span></label>
                                                <p class="m-none mail-date">@item.Created</p>
                                            </div>

                                            <div class="todo-actions">

                                                <a class="mb-xs mt-xs mr-xs modal-sizes btn-sm btn btn-danger" href="#modalXS"> <i class="fa fa-times"></i></a>

                                            </div>


                                        </li>

                                    </ul>
                                    <!-- Modal XS -->
                                    <div id="modalXS" class="modal-block modal-block-xs mfp-hide">
                                        <section class="panel">

                                            <div class="panel-body">
                                                <div class="modal-wrapper">
                                                    <div class="modal-text">
                                                        <p>Remove This Notification?</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <footer class="panel-footer">
                                                <div class="row">

                                                    <div class="col-md-12 text-right">
                                                        @Html.Partial("_NotificationDeletePartial", item)


                                                    </div>
                                                </div>
                                            </footer>
                                        </section>
                                    </div>
                                }









                            </div>
                        </div>
                      
                    
                </div>
            </div>
        </section>
    </div>



</section>